# Generated by Django 4.0.6 on 2023-05-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0004_pickuplocation_carlocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlocation',
            old_name='car',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='carlocation',
            old_name='location',
            new_name='car_location',
        ),
        migrations.AddField(
            model_name='carlocation',
            name='car_name',
            field=models.CharField(default='Default Car Name', max_length=100),
        ),
        migrations.AddField(
            model_name='carlocation',
            name='extra_km_rate',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='carlocation',
            name='hourly_rate',
            field=models.IntegerField(default=100),
        ),
    ]
