# Generated by Django 4.2.1 on 2023-05-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0005_rename_car_carlocation_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadharCardNo',
            field=models.ImageField(upload_to='aadhar card'),
        ),
        migrations.AlterField(
            model_name='user',
            name='drivingLicenseNo',
            field=models.ImageField(upload_to='driving license'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
    ]
