# Generated by Django 4.2.1 on 2023-05-30 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_user_email_code_alter_user_aadharcardno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadharCardNo',
        ),
        migrations.AlterField(
            model_name='user',
            name='drivingLicenseNo',
            field=models.ImageField(upload_to='driving_license'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileNo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
