# Generated by Django 4.0.6 on 2023-06-01 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0010_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_information', models.CharField(max_length=255)),
                ('operating_hours', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('return_location', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('pickup_time', models.DateField()),
                ('return_time', models.DateField()),
                ('rental_status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_status', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_portal.rentalbooking')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(max_length=50)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='carrentalrequest',
            name='pick_up_location',
        ),
        migrations.DeleteModel(
            name='CarLocation',
        ),
        migrations.DeleteModel(
            name='CarRentalRequest',
        ),
        migrations.DeleteModel(
            name='PickUpLocation',
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_portal.vehicle'),
        ),
    ]
