# Generated by Django 4.0.6 on 2023-06-01 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0011_location_rentalbooking_rentaltransaction_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_code', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=0)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('drivingLicenseNo', models.ImageField(upload_to='driving_license')),
            ],
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='return_time',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_portal.customer'),
        ),
    ]
