# Generated by Django 4.0.6 on 2023-06-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0013_rename_make_vehicle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='fuelType',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rentPerHour',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
