# Generated by Django 4.2.1 on 2023-06-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0019_rentaltransaction_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaltransaction',
            name='is_paid',
            field=models.BooleanField(default=0),
        ),
    ]
