# Generated by Django 4.2.1 on 2023-06-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0020_rentaltransaction_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalbooking',
            name='rental_status',
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='is_booked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='base_package_free_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='excess_km_charge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='medium_package',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='medium_package_free_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='unlimited_package',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
