# Generated by Django 4.2.1 on 2023-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0021_remove_rentalbooking_rental_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaltransaction',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
